language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "10"
git:
  depth: 3
before_script: npm install
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
notifications:
  email:
    recipients:
      - earleyj@umich.edu
    on_success: always
    on_failure: always